// GENERATED by scripts/sync-product-logic.mjs — do not edit by hand.
// Source: Jobmate-ltd/jobsafe src/lib/format/date.ts at commit 4e7a43cf1fcca064e10cf4ad3b9a8b8c979aa101
// Synced 25/09/2026. Re-sync: node scripts/sync-product-logic.mjs --from ../jobsafe
// Partial: the calendar-date helpers (YYYY-MM-DD, no time, no zone) that riddorDeadline() depends on.
const pad2 = (n: number): string => String(n).padStart(2, '0');

export type CalendarDate = string;

const CAL = /^(\d{4})-(\d{2})-(\d{2})$/;

/** Parse a calendar date to its Y/M/D triple, or null when malformed or impossible. */
export function parseCalendar(value: CalendarDate): { y: number; m: number; d: number } | null {
  const m = CAL.exec(value);
  if (!m) return null;
  const y = Number(m[1]);
  const mo = Number(m[2]);
  const d = Number(m[3]);
  if (mo < 1 || mo > 12) return null;
  if (d < 1 || d > new Date(Date.UTC(y, mo, 0)).getUTCDate()) return null;
  return { y, m: mo, d };
}

function fromUtc(ms: number): CalendarDate {
  const dt = new Date(ms);
  return `${dt.getUTCFullYear()}-${pad2(dt.getUTCMonth() + 1)}-${pad2(dt.getUTCDate())}`;
}

function toUtc(value: CalendarDate): number {
  const p = parseCalendar(value);
  if (!p) throw new RangeError(`Not a calendar date: ${value}`);
  return Date.UTC(p.y, p.m - 1, p.d);
}

/** Today's local calendar date. */
export function todayLocal(now: Date = new Date()): CalendarDate {
  return `${now.getFullYear()}-${pad2(now.getMonth() + 1)}-${pad2(now.getDate())}`;
}

/** Add whole days to a calendar date. Zone-independent. */
export function addCalendarDays(value: CalendarDate, days: number): CalendarDate {
  return fromUtc(toUtc(value) + days * 86_400_000);
}

/** Whole days from `from` to `to` (positive when `to` is later). */
export function calendarDaysBetween(from: CalendarDate, to: CalendarDate): number {
  return Math.round((toUtc(to) - toUtc(from)) / 86_400_000);
}
