// GENERATED by scripts/sync-product-logic.mjs — do not edit by hand.
// Source: Jobmate-ltd/jobsafe src/lib/domain/enums.ts at commit 4e7a43cf1fcca064e10cf4ad3b9a8b8c979aa101
// Synced 25/09/2026. Re-sync: node scripts/sync-product-logic.mjs --from ../jobsafe
// Partial: HIERARCHY / Hierarchy and RIDDOR_CATEGORIES / RiddorCategory.
export const HIERARCHY = [
  'Eliminate',
  'Substitute',
  'Engineering',
  'Administrative',
  'PPE',
] as const;

export type Hierarchy = (typeof HIERARCHY)[number];

export const RIDDOR_CATEGORIES = [
  'Death',
  'Specified',
  'Over7Day',
  'NonWorker',
  'DangerousOccurrence',
  'OccDisease',
  'GasIncident',
  'Over3DayRecordOnly',
  'NotReportable',
] as const;

export type RiddorCategory = (typeof RIDDOR_CATEGORIES)[number];
