// GENERATED by scripts/sync-product-logic.mjs — do not edit by hand.
// Source: Jobmate-ltd/jobsafe src/lib/domain/riddor/knowledge.ts at commit 4e7a43cf1fcca064e10cf4ad3b9a8b8c979aa101
// Synced 25/09/2026. Re-sync: node scripts/sync-product-logic.mjs --from ../jobsafe
// Whole file. RIDDOR 2013 categories, specified injuries, diseases, dangerous occurrences, record duties, HSE contact, deadlines and the triage sequence.
import type { RiddorCategory } from './enums.ts';
import { addCalendarDays, calendarDaysBetween } from './date.ts';

export interface RiddorCategoryDef {
  key: RiddorCategory;
  label: string;
  short: string;
  reg: string;
  notify: string;
  /** Days from the incident to get the form to HSE; null when nothing is sent. */
  formDays: number | null;
  /** Must also be phoned through to the Incident Contact Centre without delay. */
  phone: boolean;
  recordOnly: boolean;
  test: string;
  form: 'injury' | 'dangerous' | 'disease' | 'gas' | null;
}

export const RIDDOR_CATEGORY_DEFS: Record<RiddorCategory, RiddorCategoryDef> = {
  Death: {
    key: 'Death',
    label: 'Death of any person',
    short: 'Fatality',
    reg: 'Reg. 6(1)',
    notify: 'Without delay, by telephone',
    formDays: 10,
    phone: true,
    recordOnly: false,
    test: 'Any work-related death (suicides excepted). Also reportable if a person dies within one year (365 days) of a reportable work-related injury.',
    form: 'injury',
  },
  Specified: {
    key: 'Specified',
    label: 'Specified injury to a worker',
    short: 'Specified injury',
    reg: 'Reg. 4',
    notify: 'Without delay, by telephone',
    formDays: 10,
    phone: true,
    recordOnly: false,
    test: 'One of the eight specified injuries listed in Regulation 4.',
    form: 'injury',
  },
  Over7Day: {
    key: 'Over7Day',
    label: 'Over-7-day incapacitation of a worker',
    short: 'Over-7-day',
    reg: 'Reg. 4(2)',
    notify: 'Within 15 days of the accident',
    formDays: 15,
    phone: false,
    recordOnly: false,
    test: 'Worker away from work or unable to perform their normal duties for more than 7 consecutive days. The day of the accident is excluded; weekends and rest days are included.',
    form: 'injury',
  },
  NonWorker: {
    key: 'NonWorker',
    label: 'Injury to a person not at work',
    short: 'Non-worker',
    reg: 'Reg. 5',
    notify: 'Within 10 days of the accident',
    formDays: 10,
    phone: false,
    recordOnly: false,
    test: 'A member of the public or other non-worker injured by a work activity and taken directly from the scene to hospital for treatment of that injury. Diagnostic tests such as X-rays are not treatment.',
    form: 'injury',
  },
  DangerousOccurrence: {
    key: 'DangerousOccurrence',
    label: 'Dangerous occurrence',
    short: 'Dangerous occurrence',
    reg: 'Reg. 7 / Schedule 2',
    notify: 'Within 10 days of the occurrence',
    formDays: 10,
    phone: false,
    recordOnly: false,
    test: 'One of the incidents listed in Schedule 2, reportable whether or not anyone was injured.',
    form: 'dangerous',
  },
  OccDisease: {
    key: 'OccDisease',
    label: 'Occupational disease',
    short: 'Disease',
    reg: 'Reg. 8 / 9',
    notify: 'Within 10 days of the diagnosis',
    formDays: 10,
    phone: false,
    recordOnly: false,
    test: 'A listed disease diagnosed in writing by a doctor where work is the likely cause.',
    form: 'disease',
  },
  GasIncident: {
    key: 'GasIncident',
    label: 'Flammable gas incident',
    short: 'Gas incident',
    reg: 'Reg. 11',
    notify: 'Within 14 days',
    formDays: 14,
    phone: false,
    recordOnly: false,
    test: 'Gas distributors, fillers, importers and suppliers must report where someone has died, lost consciousness, or been taken to hospital for treatment.',
    form: 'gas',
  },
  Over3DayRecordOnly: {
    key: 'Over3DayRecordOnly',
    label: 'Over-3-day incapacitation, record only',
    short: 'Record only',
    reg: 'Reg. 12',
    notify: 'Not reportable to HSE',
    formDays: null,
    phone: false,
    recordOnly: true,
    test: 'Worker away or unable to do normal duties for more than 3 consecutive days but not more than 7. Must be recorded in the accident book but is not reported to HSE.',
    form: null,
  },
  NotReportable: {
    key: 'NotReportable',
    label: 'Not reportable under RIDDOR',
    short: 'Not reportable',
    reg: '–',
    notify: 'No HSE report required',
    formDays: null,
    phone: false,
    recordOnly: true,
    test: 'Does not meet any reportable threshold. Still record it internally for investigation and trend analysis.',
    form: null,
  },
};

export const SPECIFIED_INJURIES = [
  { id: 'fracture', label: 'A fracture, other than to fingers, thumbs or toes' },
  { id: 'amputation', label: 'Amputation of an arm, hand, finger, thumb, leg, foot or toe' },
  {
    id: 'sight',
    label:
      'Any injury likely to cause permanent blinding or reduction of sight in one or both eyes',
  },
  {
    id: 'crush',
    label: 'Any crush injury to the head or torso causing damage to the brain or internal organs',
  },
  {
    id: 'burns',
    label:
      'Serious burns (including scalding) covering more than 10% of the body, or causing significant damage to the eyes, respiratory system or other vital organs',
  },
  { id: 'scalping', label: 'Any scalping requiring hospital treatment' },
  { id: 'unconscious', label: 'Any loss of consciousness caused by head injury or asphyxia' },
  {
    id: 'enclosed',
    label:
      'Any other injury from working in an enclosed space leading to hypothermia or heat-induced illness, or requiring resuscitation or admittance to hospital for more than 24 hours',
  },
] as const;

export const OCC_DISEASES = [
  {
    id: 'cts',
    label: 'Carpal tunnel syndrome',
    when: 'Where work involves regular use of hand-held percussive or vibrating power tools.',
  },
  {
    id: 'cramp',
    label: 'Cramp of the hand or forearm',
    when: 'Where work involves prolonged periods of repetitive movement of the fingers, hand or arm.',
  },
  {
    id: 'dermatitis',
    label: 'Occupational dermatitis',
    when: 'Where work involves significant or regular exposure to a known skin sensitiser or irritant.',
  },
  {
    id: 'havs',
    label: 'Hand-arm vibration syndrome (HAVS)',
    when: 'Where work involves regular use of percussive or vibrating power tools, or holding materials which vibrate.',
  },
  {
    id: 'asthma',
    label: 'Occupational asthma',
    when: 'Where work involves significant or regular exposure to a known respiratory sensitiser.',
  },
  {
    id: 'tendonitis',
    label: 'Tendonitis or tenosynovitis of the hand or forearm',
    when: 'Where work is physically demanding and involves frequent, repetitive movements.',
  },
  {
    id: 'cancer',
    label: 'Occupational cancer',
    when: 'Where there is an established causal link between the cancer and a work exposure to a known carcinogen or mutagen.',
  },
  {
    id: 'bio',
    label: 'Disease attributed to a biological agent',
    when: 'Where there is reasonable evidence that an occupational exposure to a biological agent was the likely cause.',
  },
] as const;

export const DANGEROUS_OCCURRENCES = [
  {
    para: 1,
    label: 'Collapse or overturn of lifting equipment, or failure of a load-bearing part',
    note: 'Includes cranes, FLT mast or chain failures, piling rigs. Excludes lifting accessories such as chains and slings.',
  },
  {
    para: 2,
    label: 'Failure of a pressure system with the potential to cause death',
    note: 'Any vessel other than a pipeline, whatever its contents.',
  },
  {
    para: 3,
    label: 'Contact or near-contact of plant or equipment with an overhead electric line',
    note: 'Uninsulated line over 200 volts, or close proximity causing an electrical discharge.',
  },
  {
    para: 4,
    label: 'Electrical short circuit or overload causing fire or explosion',
    note: 'Reportable if the equipment is unusable for over 24 hours, or the event had the potential to cause death.',
  },
  {
    para: 10,
    label:
      'Release or escape of a biological agent likely to cause severe human infection or illness',
    note: 'Hazard Group 3 and 4 agents as defined in COSHH Schedule 3.',
  },
  {
    para: 11,
    label: 'Malfunction of a radiation generator or industrial radiography equipment',
    note: 'Failure to de-energise or failure of a source to return to its safe position.',
  },
  {
    para: 12,
    label: 'Malfunction of breathing apparatus causing significant risk of injury',
    note: 'Including malfunction found during testing immediately before use.',
  },
  {
    para: 18,
    label: 'Complete or partial collapse of scaffolding over 5 metres high',
    note: 'Also any suspended scaffold whose suspension fails causing a platform to fall.',
  },
  {
    para: 19,
    label: 'Collision of a train with another train or vehicle',
    note: 'Only rail-mounted locomotives within factory or dock premises, construction sites, mines or quarries.',
  },
  {
    para: 23,
    label:
      'Unintentional collapse of a structure: over 5 tonnes of material, or any floor or wall of a workplace',
    note: 'Structural collapses associated with construction, maintenance or demolition work.',
  },
  {
    para: 24,
    label: 'Unintentional collapse or partial collapse of any falsework',
    note: 'Applies whether construction work is taking place or not.',
  },
  {
    para: 25,
    label: 'Explosion or fire causing suspension of normal work for more than 24 hours',
    note: 'Any fire at a factory, warehouse or office building that stops work activities for over 24 hours.',
  },
  {
    para: 26,
    label:
      'Release of a flammable liquid or gas which, if ignited, would cause a major fire or explosion',
    note: 'Includes highly and extremely flammable substances.',
  },
  {
    para: 27,
    label:
      'Accidental release of any substance which could cause personal injury other than through fire or explosion',
    note: 'Substances hazardous to health, corrosives, or substances hazardous by temperature or pressure. Includes failure to contain a substance on a vehicle while at a workplace.',
  },
] as const;

export const KIND_OF_ACCIDENT = [
  'Contact with moving machinery or material being machined',
  'Hit by a moving, flying or falling object',
  'Hit by a moving vehicle',
  'Hit something fixed or stationary',
  'Injured while handling, lifting or carrying',
  'Slipped, tripped or fell on the same level',
  'Fell from a height',
  'Trapped by something collapsing or overturning',
  'Drowned or asphyxiated',
  'Exposed to, or in contact with, a harmful substance',
  'Exposed to fire',
  'Exposed to an explosion',
  'Contact with electricity or an electrical discharge',
  'Injured by an animal',
  'Physically assaulted by a person',
  'Another kind of accident',
] as const;

export const EMPLOYMENT_STATUS = [
  'Employee',
  'Self-employed',
  'Trainee (work experience)',
  'Member of the public',
  'Employee of another employer',
] as const;

export const BODY_PARTS = [
  'Head',
  'Eye',
  'Face',
  'Neck',
  'Shoulder',
  'Back',
  'Torso / chest',
  'Abdomen',
  'Arm',
  'Elbow',
  'Wrist',
  'Hand',
  'Finger or thumb',
  'Hip',
  'Leg',
  'Knee',
  'Ankle',
  'Foot',
  'Toe',
  'Multiple locations',
  'Internal organs',
] as const;

export const INJURY_NATURE = [
  'Fracture',
  'Amputation',
  'Dislocation',
  'Laceration / open wound',
  'Bruising / contusion',
  'Sprain or strain',
  'Burn or scald',
  'Crush injury',
  'Concussion / head injury',
  'Loss of consciousness',
  'Eye injury',
  'Electric shock',
  'Asphyxiation',
  'Poisoning / chemical exposure',
  'Multiple injuries',
  'Other',
] as const;

export const RECORD_REQUIREMENTS = {
  duty: 'Regulation 12 imposes a standalone duty to keep a record of every reportable injury, disease and dangerous occurrence, separate from the report sent to HSE.',
  retention:
    'Keep for at least 3 years from the date the record was made. HSE legal advisers commonly recommend 6 years to align with the Limitation Act 1980 window for civil claims.',
  fields: [
    'Date and time of the incident',
    'Full personal details of the injured person (name, address, occupation)',
    'The nature of the injury, disease or dangerous occurrence',
    'The place where the incident happened',
    'A brief description of the circumstances',
    'The date the report was made to HSE and the RIDDOR reference number issued',
  ],
  accidentBook:
    'The accident book (BI 510) is a separate duty under the Social Security (Claims and Payments) Regulations 1979 for employers with 10 or more employees. It can serve as the RIDDOR record for injuries, but not for diseases or dangerous occurrences, and logging it there does not satisfy the duty to report to HSE.',
} as const;

export const HSE_CONTACT = {
  phone: '0345 300 9923',
  phoneHours: 'Monday to Friday, 08:30 to 17:00',
  portal: 'https://notifications.hse.gov.uk/riddorforms',
  forms: {
    injury: 'F2508, report of an injury',
    dangerous: 'F2508, report of a dangerous occurrence',
    disease: 'F2508A, report of a case of disease',
    gas: 'F2508G, report of a flammable gas incident',
  },
} as const;

/* ---- deadlines ---------------------------------------------------------- */

export interface Deadline {
  /** ISO date the form must reach HSE by, or null when nothing is sent. */
  deadlineAt: string | null;
  /** Whole days left (negative when past), or null. */
  daysLeft: number | null;
  overdue: boolean;
}

/** `occurredAt` and `today` are calendar dates (YYYY-MM-DD). */
export function riddorDeadline(
  category: RiddorCategory,
  occurredAt: string,
  today: string,
): Deadline {
  const def = RIDDOR_CATEGORY_DEFS[category];
  if (def.formDays === null) return { deadlineAt: null, daysLeft: null, overdue: false };
  const deadlineAt = addCalendarDays(occurredAt, def.formDays);
  const daysLeft = calendarDaysBetween(today, deadlineAt);
  return { deadlineAt, daysLeft, overdue: daysLeft < 0 };
}

/* ---- triage --------------------------------------------------------------- */

export interface TriageAnswers {
  workRelated?: 'yes' | 'no';
  roadTraffic?: 'yes' | 'no';
  privateRoad?: 'yes' | 'no';
  outcome?: 'death' | 'injury' | 'none';
  personType?: 'worker' | 'nonworker';
  specifiedInjuries?: string[];
  hospitalTreatment?: 'yes' | 'no';
  category?: 'injury' | 'disease' | 'dangerous';
  diseaseDiagnosed?: 'yes' | 'no';
  disease?: string;
  dangerousPara?: number | string;
  daysOff?: number | string | null;
  stillOff?: 'yes' | 'no';
}

export interface TriageResult {
  category: RiddorCategory;
  def: RiddorCategoryDef;
  reasons: string[];
  provisional?: boolean;
  specified?: string[];
}

/**
 * Mirrors the HSE decision sequence: work-related? fatality? specified injury?
 * non-worker to hospital? over-7-day? disease? dangerous occurrence? else record only.
 */
export function triage(a: TriageAnswers): TriageResult {
  const out = (
    category: RiddorCategory,
    reasons: string[],
    extra: Partial<TriageResult> = {},
  ): TriageResult => ({
    category,
    def: RIDDOR_CATEGORY_DEFS[category],
    reasons,
    ...extra,
  });

  if (a.workRelated === 'no') {
    return out('NotReportable', [
      'The incident did not arise out of or in connection with work, so RIDDOR does not apply.',
    ]);
  }
  if (a.roadTraffic === 'yes' && a.privateRoad !== 'yes') {
    return out('NotReportable', [
      'Injuries from vehicle movement on a public road are not reportable under RIDDOR. Report to the police instead.',
      'If the incident happened on a genuinely private road or yard where the public has no access, it is reportable.',
    ]);
  }
  if (a.outcome === 'death') {
    return out('Death', [
      'A work-related death must be reported without delay by telephone to the HSE Incident Contact Centre.',
    ]);
  }
  const specified = a.specifiedInjuries ?? [];
  if (a.personType === 'worker' && specified.length > 0) {
    const names: string[] = [];
    for (const id of specified) {
      const label = SPECIFIED_INJURIES.find((s) => s.id === id)?.label;
      if (label) names.push(label);
    }
    return out('Specified', [`Regulation 4 specified injury: ${names.join('; ')}.`], {
      specified: names,
    });
  }
  if (a.personType === 'nonworker') {
    if (a.hospitalTreatment === 'yes') {
      return out('NonWorker', [
        'A non-worker was injured by a work activity and taken directly from the scene to hospital for treatment.',
      ]);
    }
    return out('NotReportable', [
      'The person was not at work, but was not taken directly from the scene to hospital for treatment of the injury.',
      'Diagnostic tests such as X-rays do not count as treatment, and precautionary attendance with no apparent injury is not reportable.',
    ]);
  }
  if (a.category === 'disease' && a.diseaseDiagnosed === 'yes') {
    const d = OCC_DISEASES.find((x) => x.id === a.disease);
    return out('OccDisease', [
      `A doctor has diagnosed ${d ? d.label : 'a listed occupational disease'} and work is the likely cause.`,
    ]);
  }
  if (a.category === 'dangerous' && a.dangerousPara !== undefined && a.dangerousPara !== '') {
    const d = DANGEROUS_OCCURRENCES.find((x) => String(x.para) === String(a.dangerousPara));
    return out('DangerousOccurrence', [
      `Schedule 2, paragraph ${a.dangerousPara}: ${d ? d.label : ''}.`,
    ]);
  }
  if (
    a.personType === 'worker' &&
    a.daysOff !== null &&
    a.daysOff !== undefined &&
    a.daysOff !== ''
  ) {
    const d = typeof a.daysOff === 'number' ? a.daysOff : parseInt(String(a.daysOff), 10) || 0;
    if (d > 7)
      return out('Over7Day', [
        `The worker was unable to perform their normal duties for ${d} consecutive days (more than 7). The report must reach HSE within 15 days of the accident.`,
      ]);
    if (d > 3)
      return out('Over3DayRecordOnly', [
        `The worker was incapacitated for ${d} consecutive days, more than 3 but not more than 7. Record it in the accident book; no HSE report is required.`,
      ]);
    if (a.stillOff === 'yes')
      return out(
        'Over7Day',
        [
          'The worker is still unable to perform normal duties. Once the absence exceeds 7 consecutive days this becomes reportable: monitor and report within 15 days of the accident.',
        ],
        { provisional: true },
      );
    return out('NotReportable', [
      `Incapacity of ${d} day${d === 1 ? '' : 's'} does not reach a reportable or recordable threshold.`,
    ]);
  }
  if (a.stillOff === 'yes') {
    return out(
      'Over7Day',
      [
        'The worker remains unable to perform normal duties. This will become reportable once the absence exceeds 7 consecutive days.',
      ],
      { provisional: true },
    );
  }
  return out('NotReportable', [
    'On the answers given, no reportable threshold under RIDDOR 2013 is met. Record it internally and investigate as normal.',
  ]);
}
