// GENERATED by scripts/sync-product-logic.mjs — do not edit by hand.
// Source: Jobmate-ltd/jobsafe src/lib/domain/risk/scoring.ts at commit 4e7a43cf1fcca064e10cf4ad3b9a8b8c979aa101
// Synced 25/09/2026. Re-sync: node scripts/sync-product-logic.mjs --from ../jobsafe
// Partial: BANDS, LIKELIHOOD_SCALE, SEVERITY_SCALE, HIERARCHY_DEFS, clamp, score and bandOf. The hazard, assessment and bowtie maths stay in the product.
import type { Hierarchy } from './enums.ts';

export type RiskBand = 'Low' | 'Medium' | 'High' | 'Extreme';

export interface BandDef {
  key: RiskBand;
  min: number;
  max: number;
  tone: 'green' | 'amber' | 'red';
  action: string;
  /** Days allowed to close further controls; null = no deadline, 0 = stop work. */
  sla: number | null;
}

export const BANDS: readonly BandDef[] = [
  {
    key: 'Low',
    min: 1,
    max: 4,
    tone: 'green',
    action: 'Broadly acceptable. Maintain existing controls and monitor.',
    sla: null,
  },
  {
    key: 'Medium',
    min: 5,
    max: 9,
    tone: 'amber',
    action: 'Reduce where reasonably practicable. Add controls and set a review date.',
    sla: 90,
  },
  {
    key: 'High',
    min: 10,
    max: 16,
    tone: 'red',
    action: 'Must be reduced. Time-bound actions required and progress tracked.',
    sla: 30,
  },
  {
    key: 'Extreme',
    min: 17,
    max: 25,
    tone: 'red',
    action: 'STOP the activity. Do not proceed until controls bring the score down.',
    sla: 0,
  },
];

export const LIKELIHOOD_SCALE = [
  {
    v: 1,
    label: 'Rare',
    desc: 'May occur only in exceptional circumstances; no known history here',
  },
  {
    v: 2,
    label: 'Unlikely',
    desc: 'Could occur at some time but not expected; rare across the industry',
  },
  {
    v: 3,
    label: 'Possible',
    desc: 'Might occur occasionally; has happened elsewhere in the network',
  },
  {
    v: 4,
    label: 'Likely',
    desc: 'Will probably occur in most circumstances; near misses already logged',
  },
  {
    v: 5,
    label: 'Almost certain',
    desc: 'Expected to occur in most circumstances; happening regularly now',
  },
] as const;

export const SEVERITY_SCALE = [
  {
    v: 1,
    label: 'Negligible',
    desc: 'No treatment needed, or self-treated. No lost time.',
    riddor: 'no',
  },
  {
    v: 2,
    label: 'Minor',
    desc: 'First aid on site. Back to normal duties the same day.',
    riddor: 'no',
  },
  {
    v: 3,
    label: 'Moderate',
    desc: 'Medical treatment. Off normal duties up to 7 days; accident book record.',
    riddor: 'record',
  },
  {
    v: 4,
    label: 'Major',
    desc: 'Regulation 4 specified injury, or over-7-day absence. RIDDOR reportable.',
    riddor: 'yes',
  },
  {
    v: 5,
    label: 'Catastrophic',
    desc: 'Fatality, multiple casualties, or permanent disabling injury.',
    riddor: 'yes',
  },
] as const;

export const HIERARCHY_DEFS: Record<Hierarchy, { rank: number; desc: string }> = {
  Eliminate: { rank: 1, desc: 'Remove the hazard completely: redesign the task or stop doing it' },
  Substitute: { rank: 2, desc: 'Replace with something less hazardous' },
  Engineering: {
    rank: 3,
    desc: 'Isolate or guard: barriers, ventilation, interlocks, segregation',
  },
  Administrative: {
    rank: 4,
    desc: 'Change the way people work: procedures, training, permits, rotation',
  },
  PPE: { rank: 5, desc: 'Last resort: protects only the wearer and relies on correct use' },
};

export function clamp(n: number, lo: number, hi: number): number {
  return Math.max(lo, Math.min(hi, n));
}

export function score(l: number, s: number): number {
  return clamp(Math.round(l), 1, 5) * clamp(Math.round(s), 1, 5);
}

export function bandOf(value: number): BandDef {
  const found = BANDS.find((b) => value >= b.min && value <= b.max);
  return found ?? BANDS[0]!;
}
